### ISSUE TITLE
outside docker...

### ISSUE THREAD

**Issue by DamienMure** [kallqvist/rundeck-rancher#13]
Hi.
Your plugin is very useful, but I needed to make it work outside docker : Just with rundeck.
So I forked it and I made changes.

I'm planning to ask for a publication on the official rundeck plugins page.
But as you made most of the job, I would like to tell you first.
I not sure if a PR is relevant because I removed everything related to docker (especially environment variables).

Best Regards
Damien

**Comment by kallqvist** [comment]
Hi, glad that you like it!

I realized that I never added any specific license to this repo but my intention was that all code here is released under any of the "do whatever you want with it for private and/or commercial use but a link back is always nice" :)
(Don't know all the licenses in detail but I guess that would be any of either BSD-2, MIT, maybe apache license or such)
When I figure out what license that is I'm going to attach it to this repo just to make it a bit more clear to everybody that the "free to do whatever" part is what it's all about)

And totally agree with you guys submitting this to rundeck from your own fork directly instead of sending a PR back, I have a very specific use-case with this in my own infrastructure where I only ever use rundeck as a docker container and that is more or less exactly what my repo is already doing for me right now so I'm pretty much not planning to accept any PR back other than bug fixes or minor changes from this point.

I remember it was alot of headache for me to figure out all the internal (and not always very well-documented) workings of the rancher web sockets.
I think the code should be pretty straightforward and easy to debug but feel free to reach out to me if you have any questions about details in my implementation and I'll try to answer them the best I can!

Good luck!

**Comment by kallqvist** [comment]
Btw, there was a couple of edge-cases in the code that I discovered and solved in a couple of commits after you made your fork.
Maybe you solved those issues somewhere in your own refactoring but if not then you probably want to check those commits out.

I also added information about your efforts and a link to your fork from my readme to better help someone else that have a similar use-case to yours :)

**Comment by DamienMure** [comment]
Thank for you reply.
I'll check your last commits.
I'lll officially ask for the plugin registration at rundeck within the next 2 weeks.
